import './admin-ui.css'

// 组件库入口：把 UI 原语、数据组件、控制台外壳与通用工具全部导出，
// 宿主既可以按需从 `@runlume/admin-ui/components/*`、`@runlume/admin-ui/ui/*`、
// `@runlume/admin-ui/lib/*` 取子路径，也可以从这里一次性引入。

export * from './components/about-panel'
export * from './components/accessibility-settings'
export * from './components/auth-layout'
export * from './components/bulk-actions'
export * from './components/calendar'
export * from './components/cascader'
export * from './components/charts'
export * from './components/code-block'
export * from './components/color-settings'
export * from './components/column-chart'
export * from './components/combobox'
export * from './components/confirm-dialog'
export * from './components/console-layout'
export * from './components/count-to'
export * from './components/cursor-pagination'
export * from './components/data-table'
export * from './components/descriptions'
export * from './components/editable-table'
export * from './components/favorites-menu'
export * from './components/filter-button'
export * from './components/filter-presets'
export * from './components/fixed-bar'
export * from './components/fullscreen-button'
export * from './components/github-link'
export * from './components/header-action-settings'
export * from './components/image-preview'
export * from './components/layout-container'
export * from './components/list-module'
export * from './components/mention'
export * from './components/menu-search'
export * from './components/multi-select'
export * from './components/multi-step-loader'
export * from './components/navigation-group'
export * from './components/notification-settings'
export * from './components/notifications-button'
export * from './components/page'
export * from './components/page-button'
export * from './components/page-pager'
export * from './components/page-reload-button'
export * from './components/page-reload-route'
export * from './components/page-tabs'
export * from './components/pagination-bar'
export * from './components/password-strength'
export * from './components/permission'
export * from './components/preferences-menu'
export * from './components/rate'
export * from './components/resizable-panel'
export * from './components/route-error'
export * from './components/row-actions'
export * from './components/search-filters'
export * from './components/sortable-list'
export * from './components/sparkline'
export * from './components/status-badge'
export * from './components/steps'
export * from './components/storage-box'
export * from './components/table-cell-overflow'
export * from './components/table-toolbar'
export * from './components/theme-provider'
export * from './components/time-ago'
export * from './components/timeline'
export * from './components/transfer'
export * from './components/tree'
export * from './components/tree-table'
export * from './components/trend'
export * from './components/user-menu'
export * from './components/user-profile'
export * from './components/user-settings'
export * from './components/ui/alert'
export * from './components/ui/alert-dialog'
export * from './components/ui/avatar'
export * from './components/ui/badge'
export * from './components/ui/breadcrumb'
export * from './components/ui/button'
export * from './components/ui/card'
export * from './components/ui/checkbox'
export * from './components/ui/collapsible'
export * from './components/ui/context-menu'
export * from './components/ui/date-input'
export * from './components/ui/date-range-input'
export * from './components/ui/date-time-input'
export * from './components/ui/dialog'
export * from './components/ui/dropdown-menu'
export * from './components/ui/file-upload'
export * from './components/ui/hover-card'
export * from './components/ui/input'
export * from './components/ui/input-otp'
export * from './components/ui/kbd'
export * from './components/ui/label'
export * from './components/ui/native-select'
export * from './components/ui/number-field'
export * from './components/ui/progress'
export * from './components/ui/radio-group'
export * from './components/ui/scroll-area'
export * from './components/ui/select'
export * from './components/ui/separator'
export * from './components/ui/sheet'
export * from './components/ui/sidebar'
export * from './components/ui/skeleton'
export * from './components/ui/slider'
export * from './components/ui/sonner'
export * from './components/ui/switch'
export * from './components/ui/table'
export * from './components/ui/tabs'
export * from './components/ui/tag'
export * from './components/ui/tag-variants'
export * from './components/ui/textarea'
export * from './components/ui/time-input'
export * from './components/ui/tooltip'

export * from './lib/accessibility'
export * from './lib/appearance'
export * from './lib/color-options'
export * from './lib/content-search'
export * from './lib/dialog-focus'
export * from './lib/hotkeys'
export * from './lib/metrics'
export * from './lib/nav-icons'
// `NavigationGroup` 与组件同名，这里只导出不与组件冲突的名字；
// 需要类型版的 `NavigationGroup` 时从 `@runlume/admin-ui/lib/navigation` 取。
export type {
  NavigationIcon,
  NavigationItem,
  NavigationLinkTarget,
  NavigationGroupDefinition,
  FlatNavigationEntry,
} from './lib/navigation'
export {
  containsActivePath,
  flattenNavigation,
  groupNavigation,
  isLeavingApp,
  navigationPaths,
  resolveActiveItem,
  singleGroup,
} from './lib/navigation'
export * from './lib/notification-preferences'
export * from './lib/overlay-suppression'
export * from './lib/pager'
// `PasswordStrength` 与组件同名，只导出规则与强度计算；类型从子路径取。
export { passwordRules, passwordStrength } from './lib/password'
export type { PasswordRule } from './lib/password'
export * from './lib/permission-context'
export * from './lib/permissions'
export * from './lib/preset-shortcuts'
export * from './lib/presets'
export * from './lib/range'
export * from './lib/redirect'
export * from './lib/shell-messages'
export * from './lib/storage-key'
export * from './lib/table-prefs'
export * from './lib/time'
export * from './lib/tree'
export * from './lib/use-ui-translation'
export * from './lib/utils'
export * from './hooks/use-mobile'
export * from './hooks/use-resolved-theme'
